version: '3.8'

services:
  xero-mock:
    image: jaypeng2015/show-me-the-money
    container_name: xero-mock
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - XERO_API_URL=http://xero-mock:3000/api.xro/2.0/Reports/BalanceSheet
      - NODE_ENV=development
    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
    depends_on:
      - xero-mock
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=3001
      - WDS_SOCKET_HOST=localhost
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - FAST_REFRESH=false
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 